### PR TITLE
Fix Sort, Edit and Showlist issue Bug

### LINKED ISSUE #171: [Bug] Sort, Edit and Showlist issue
### Bug 1: Sort then Edit
Sorting the list and editing the specified index does not edit the index of the displayed list. Instead it edits the unsorted list.

#### Recreation of bug 
1. Sort the list `sort`
2. Edit the first show. (make sure first show does not have same index before and after sorting)
3. Unsorted first show is edited.

### Bug 2: Weird sort interaction with numbered show name
Sorting the list when a show start with numbers will break the list command from showing the original unsort list.

#### Recreation of bug 
1. Add a show that starts with number `add n/86 Eighty Six s/completed`
2. Sort the list `sort` and list the shows `list`
3. This will result in the unsorted list being shown.
4. Repeat step 2 another time.
5. The list being shown will be stuck as the sorted list instead of the unsorted list.

Note: when trackermon is reloaded, the unsorted list is shown at startup.

### Expected Outcome:
If I recall: 
- List should display the shows as it was added (unsorted).
- Edit will edit the show based on the displayed index.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by JonathanHoshi — APPROVED** [review]
LGTM!

File: src/main/java/seedu/trackermon/model/Model.java [hunk 1]
```diff
@@ -97,5 +97,8 @@
      * @throws NullPointerException if {@code comparator} is null.
      */
     void updateSortedShowList(Comparator<Show> comparator);
-
+    /**
+     * Saves the sort of the sorted show list.
```
Comment (arcornior) [inline src/main/java/seedu/trackermon/model/Model.java:101]: Should this be `Saves the order of the sorted show list` instead?

**Review by arcornior — APPROVED** [review]
LGTM! Might want to check the phrasing of the JavaDoc comment though!
